# Release to github using semantic versioning and conventional commits

name: GitHub Release
on:
  push:
    branches:
      - main

jobs:
  changelog:
    if: github.repository_owner == 'krshkun'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - run: yarn install --frozen-lockfile
      - run: yarn release
        env:
          GIT_AUTHOR_NAME: 'Krish Gupta'
          GIT_AUTHOR_EMAIL: 'krshkun@proton.me'
          GIT_COMMITTER_NAME: 'Krish Gupta'
          GIT_COMMITTER_EMAIL: 'krshkun@proton.me'
