name: Continuous Deployment
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Packages
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - run: yarn install --frozen-lockfile
      - run: yarn build
  test:
    needs: build
    name: Test Packages
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: yarn test

  release:
    needs:
      - build
      - test
    name: Release Packages
    if: github.repository_owner == 'krshkun'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: yarn release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GH_NPM_TOKEN: ${{ secrets.GH_NPM_TOKEN } }}
          NPM_TOKEN: ${{ secrets.PUBLIC_NPM_TOKEN }}
          GIT_AUTHOR_NAME: 'Krish Gupta'
          GIT_AUTHOR_EMAIL: 'krshkun@proton.me'
          GIT_COMMITTER_NAME: 'Krish Gupta'
          GIT_COMMITTER_EMAIL: 'krshkun@proton.me'
