# Release to github using semantic versioning and conventional commits

name: GitHub Release
on:
  push:
    branches:
      - main

jobs:
  changelog:
    if: github.repository_owner == 'krshkun'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - run: yarn install
      - run: yarn bump
      - run: yarn changelog
      - run: yarn release
